package robot.com.myapplication.adapter;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import robot.com.myapplication.R;

public class FaceUtils {
    private static List <MyIconModel> mList = new ArrayList<>();

    public static List <MyIconModel> initFaceData(){
        mList.add(new MyIconModel( R.drawable.face_0));
        mList.add(new MyIconModel( R.drawable.face_1));
        mList.add(new MyIconModel( R.drawable.face_2));
        mList.add(new MyIconModel( R.drawable.face_3));
        mList.add(new MyIconModel( R.drawable.face_4));
        mList.add(new MyIconModel( R.drawable.face_5));
        mList.add(new MyIconModel( R.drawable.face_6));
        mList.add(new MyIconModel( R.drawable.face_7));
        mList.add(new MyIconModel( R.drawable.face_8));
        mList.add(new MyIconModel( R.drawable.face_9));
        mList.add(new MyIconModel( R.drawable.face_10));
        mList.add(new MyIconModel( R.drawable.face_11));
        mList.add(new MyIconModel( R.drawable.face_12));
        mList.add(new MyIconModel( R.drawable.face_13));
        mList.add(new MyIconModel( R.drawable.face_14));
        mList.add(new MyIconModel( R.drawable.face_15));
        mList.add(new MyIconModel( R.drawable.face_16));
        mList.add(new MyIconModel( R.drawable.face_17));
        mList.add(new MyIconModel( R.drawable.face_18));
        mList.add(new MyIconModel( R.drawable.face_19));
        mList.add(new MyIconModel( R.drawable.delete_expression));
        mList.add(new MyIconModel( R.drawable.face_20));
        mList.add(new MyIconModel( R.drawable.face_21));
        mList.add(new MyIconModel( R.drawable.face_22));
        mList.add(new MyIconModel( R.drawable.face_23));
        mList.add(new MyIconModel( R.drawable.face_24));
        mList.add(new MyIconModel( R.drawable.face_25));
        mList.add(new MyIconModel( R.drawable.face_26));
        mList.add(new MyIconModel( R.drawable.face_27));
        mList.add(new MyIconModel( R.drawable.face_28));
        mList.add(new MyIconModel( R.drawable.face_29));
        mList.add(new MyIconModel( R.drawable.face_30));
        mList.add(new MyIconModel( R.drawable.face_31));
        mList.add(new MyIconModel( R.drawable.face_32));
        mList.add(new MyIconModel( R.drawable.face_33));
        mList.add(new MyIconModel( R.drawable.face_34));
        mList.add(new MyIconModel( R.drawable.face_35));
        mList.add(new MyIconModel( R.drawable.face_36));
        mList.add(new MyIconModel( R.drawable.face_37));
        mList.add(new MyIconModel( R.drawable.face_38));
        mList.add(new MyIconModel( R.drawable.face_39));
        mList.add(new MyIconModel( R.drawable.delete_expression));
        mList.add(new MyIconModel( R.drawable.face_40));
        mList.add(new MyIconModel( R.drawable.face_41));
        mList.add(new MyIconModel( R.drawable.face_42));
        mList.add(new MyIconModel( R.drawable.face_43));
        mList.add(new MyIconModel( R.drawable.face_44));
        mList.add(new MyIconModel( R.drawable.face_45));
        mList.add(new MyIconModel( R.drawable.face_46));
        mList.add(new MyIconModel( R.drawable.face_47));
        mList.add(new MyIconModel( R.drawable.face_48));
        mList.add(new MyIconModel( R.drawable.face_49));
        mList.add(new MyIconModel( R.drawable.face_50));
        mList.add(new MyIconModel( R.drawable.face_51));
        mList.add(new MyIconModel( R.drawable.face_52));
        mList.add(new MyIconModel( R.drawable.face_53));
        mList.add(new MyIconModel( R.drawable.face_54));
        mList.add(new MyIconModel( R.drawable.face_55));
        mList.add(new MyIconModel( R.drawable.face_56));
        mList.add(new MyIconModel( R.drawable.face_57));
        mList.add(new MyIconModel( R.drawable.face_58));
        mList.add(new MyIconModel( R.drawable.face_59));
        mList.add(new MyIconModel( R.drawable.delete_expression));
        mList.add(new MyIconModel( R.drawable.face_60));
        mList.add(new MyIconModel( R.drawable.face_61));
        mList.add(new MyIconModel( R.drawable.face_62));
        mList.add(new MyIconModel( R.drawable.face_63));
        mList.add(new MyIconModel( R.drawable.face_64));
        mList.add(new MyIconModel( R.drawable.face_65));
        mList.add(new MyIconModel( R.drawable.face_66));
        mList.add(new MyIconModel( R.drawable.face_67));
        mList.add(new MyIconModel( R.drawable.face_68));
        mList.add(new MyIconModel( R.drawable.face_69));
        mList.add(new MyIconModel( R.drawable.face_70));
        mList.add(new MyIconModel( R.drawable.face_71));
        mList.add(new MyIconModel( R.drawable.face_72));
        mList.add(new MyIconModel( R.drawable.face_73));
        mList.add(new MyIconModel( R.drawable.face_74));
        mList.add(new MyIconModel( R.drawable.face_75));
        mList.add(new MyIconModel( R.drawable.face_76));
        mList.add(new MyIconModel( R.drawable.face_77));
        mList.add(new MyIconModel( R.drawable.face_79));
        mList.add(new MyIconModel( R.drawable.face_80));
        mList.add(new MyIconModel( R.drawable.delete_expression));
        mList.add(new MyIconModel( R.drawable.face_81));
        mList.add(new MyIconModel( R.drawable.face_82));
        mList.add(new MyIconModel( R.drawable.face_83));
        mList.add(new MyIconModel( R.drawable.face_84));
        mList.add(new MyIconModel( R.drawable.face_85));
        mList.add(new MyIconModel( R.drawable.face_86));
        mList.add(new MyIconModel( R.drawable.face_87));
        mList.add(new MyIconModel( R.drawable.face_88));
        mList.add(new MyIconModel( R.drawable.face_89));
        mList.add(new MyIconModel( R.drawable.face_90));
        mList.add(new MyIconModel( R.drawable.face_91));
        mList.add(new MyIconModel( R.drawable.face_92));
        mList.add(new MyIconModel( R.drawable.face_93));
        mList.add(new MyIconModel( R.drawable.face_94));
        mList.add(new MyIconModel( R.drawable.face_95));
        mList.add(new MyIconModel( R.drawable.face_96));
        mList.add(new MyIconModel( R.drawable.face_97));
        mList.add(new MyIconModel( R.drawable.face_98));
        mList.add(new MyIconModel( R.drawable.face_99));
        mList.add(new MyIconModel( R.drawable.face_100));
        mList.add(new MyIconModel( R.drawable.delete_expression));
        return mList;
    }

    public static Map<Integer, Integer> gifFaceInfo = new HashMap<Integer, Integer>();

    static {
        addString(gifFaceInfo, 0, R.drawable.face_0);
        addString(gifFaceInfo, 1, R.drawable.face_1);
        addString(gifFaceInfo, 2, R.drawable.face_2);
        addString(gifFaceInfo, 3, R.drawable.face_3);
        addString(gifFaceInfo, 4, R.drawable.face_4);
        addString(gifFaceInfo, 5, R.drawable.face_5);
        addString(gifFaceInfo, 6, R.drawable.face_6);
        addString(gifFaceInfo, 7, R.drawable.face_7);
        addString(gifFaceInfo, 8, R.drawable.face_8);
        addString(gifFaceInfo, 9, R.drawable.face_9);
        addString(gifFaceInfo, 10, R.drawable.face_10);
        addString(gifFaceInfo, 11, R.drawable.face_11);
        addString(gifFaceInfo, 12, R.drawable.face_12);
        addString(gifFaceInfo, 13, R.drawable.face_13);
        addString(gifFaceInfo, 14, R.drawable.face_14);
        addString(gifFaceInfo, 15, R.drawable.face_15);
        addString(gifFaceInfo, 16, R.drawable.face_16);
        addString(gifFaceInfo, 17, R.drawable.face_17);
        addString(gifFaceInfo, 18, R.drawable.face_18);
        addString(gifFaceInfo, 19, R.drawable.face_19);
        addString(gifFaceInfo, 20, R.drawable.delete_expression);
        addString(gifFaceInfo, 21, R.drawable.face_20);
        addString(gifFaceInfo, 22, R.drawable.face_21);
        addString(gifFaceInfo, 23, R.drawable.face_22);
        addString(gifFaceInfo, 24, R.drawable.face_23);
        addString(gifFaceInfo, 25, R.drawable.face_24);
        addString(gifFaceInfo, 26, R.drawable.face_25);
        addString(gifFaceInfo, 27, R.drawable.face_26);
        addString(gifFaceInfo, 28, R.drawable.face_27);
        addString(gifFaceInfo, 29, R.drawable.face_28);
        addString(gifFaceInfo, 30, R.drawable.face_29);
        addString(gifFaceInfo, 31, R.drawable.face_30);
        addString(gifFaceInfo, 32, R.drawable.face_31);
        addString(gifFaceInfo, 33, R.drawable.face_32);
        addString(gifFaceInfo, 34, R.drawable.face_33);
        addString(gifFaceInfo, 35, R.drawable.face_34);
        addString(gifFaceInfo, 36, R.drawable.face_35);
        addString(gifFaceInfo, 37, R.drawable.face_36);
        addString(gifFaceInfo, 38, R.drawable.face_37);
        addString(gifFaceInfo, 39, R.drawable.face_38);
        addString(gifFaceInfo, 40, R.drawable.face_39);
        addString(gifFaceInfo, 41, R.drawable.delete_expression);
        addString(gifFaceInfo, 42, R.drawable.face_40);
        addString(gifFaceInfo, 43, R.drawable.face_41);
        addString(gifFaceInfo, 44, R.drawable.face_42);
        addString(gifFaceInfo, 45, R.drawable.face_43);
        addString(gifFaceInfo, 46, R.drawable.face_44);
        addString(gifFaceInfo, 47, R.drawable.face_45);
        addString(gifFaceInfo, 48, R.drawable.face_46);
        addString(gifFaceInfo, 49, R.drawable.face_47);
        addString(gifFaceInfo, 50, R.drawable.face_48);
        addString(gifFaceInfo, 51, R.drawable.face_49);
        addString(gifFaceInfo, 52, R.drawable.face_50);
        addString(gifFaceInfo, 53, R.drawable.face_51);
        addString(gifFaceInfo, 54, R.drawable.face_52);
        addString(gifFaceInfo, 55, R.drawable.face_53);
        addString(gifFaceInfo, 56, R.drawable.face_54);
        addString(gifFaceInfo, 57, R.drawable.face_55);
        addString(gifFaceInfo, 58, R.drawable.face_56);
        addString(gifFaceInfo, 59, R.drawable.face_57);
        addString(gifFaceInfo, 60, R.drawable.face_58);
        addString(gifFaceInfo, 61, R.drawable.face_59);
        addString(gifFaceInfo, 62, R.drawable.delete_expression);
        addString(gifFaceInfo, 63, R.drawable.face_60);
        addString(gifFaceInfo, 64, R.drawable.face_61);
        addString(gifFaceInfo, 65, R.drawable.face_62);
        addString(gifFaceInfo, 66, R.drawable.face_63);
        addString(gifFaceInfo, 67, R.drawable.face_64);
        addString(gifFaceInfo, 68, R.drawable.face_65);
        addString(gifFaceInfo, 69, R.drawable.face_66);
        addString(gifFaceInfo, 70, R.drawable.face_67);
        addString(gifFaceInfo, 71, R.drawable.face_68);
        addString(gifFaceInfo, 72, R.drawable.face_69);
        addString(gifFaceInfo, 73, R.drawable.face_70);
        addString(gifFaceInfo, 74, R.drawable.face_71);
        addString(gifFaceInfo, 75, R.drawable.face_72);
        addString(gifFaceInfo, 76, R.drawable.face_73);
        addString(gifFaceInfo, 77, R.drawable.face_74);
        addString(gifFaceInfo, 78, R.drawable.face_75);
        addString(gifFaceInfo, 79, R.drawable.face_76);
        addString(gifFaceInfo, 80, R.drawable.face_77);
        addString(gifFaceInfo, 81, R.drawable.face_79);
        addString(gifFaceInfo, 82, R.drawable.face_80);
        addString(gifFaceInfo, 83, R.drawable.delete_expression);
        addString(gifFaceInfo, 84, R.drawable.face_81);
        addString(gifFaceInfo, 85, R.drawable.face_82);
        addString(gifFaceInfo, 86, R.drawable.face_83);
        addString(gifFaceInfo, 87, R.drawable.face_84);
        addString(gifFaceInfo, 88, R.drawable.face_85);
        addString(gifFaceInfo, 89, R.drawable.face_86);
        addString(gifFaceInfo, 90, R.drawable.face_87);
        addString(gifFaceInfo, 91, R.drawable.face_88);
        addString(gifFaceInfo, 92, R.drawable.face_89);
        addString(gifFaceInfo, 93, R.drawable.face_90);
        addString(gifFaceInfo, 94, R.drawable.face_91);
        addString(gifFaceInfo, 95, R.drawable.face_92);
        addString(gifFaceInfo, 96, R.drawable.face_93);
        addString(gifFaceInfo, 97, R.drawable.face_94);
        addString(gifFaceInfo, 98, R.drawable.face_95);
        addString(gifFaceInfo, 99, R.drawable.face_96);
        addString(gifFaceInfo, 100, R.drawable.face_97);
        addString(gifFaceInfo, 101, R.drawable.face_98);
        addString(gifFaceInfo, 102, R.drawable.face_99);
        addString(gifFaceInfo, 103, R.drawable.face_100);
        addString(gifFaceInfo, 104, R.drawable.delete_expression);
    }

    private static void addString(Map<Integer, Integer> map, int position, int resource) {
        map.put(position, resource);
    }

    public static String FilterHtml(String str) {
        str = str.replaceAll("<(?!br|img)[^>]+>", "").trim();
        return str;
    }

}
